/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

export type { WrappedERC20Token } from "./WrappedERC20Token";
export { WrappedERC20Token__factory } from "./factories/WrappedERC20Token__factory";
